spring:
  datasource:
    url: jdbc:mysql://root:FPx9ABPI12PabnEpydaE@containers-us-west-123.railway.app:7965/railway
    username: root
    password: FPx9ABPI12PabnEpydaE
    name: railway
  servlet:
    multipart:
      max-file-size : 10MB
      max-request-size : 10MB

  sql:
    init:
      mode: always

server:
  max-http-header-size: 10MB